# Generated by Django 4.1.3 on 2022-12-23 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timeStamp", models.DateTimeField(auto_now_add=True)),
                ("Title", models.CharField(max_length=100)),
                ("Description", models.TextField(max_length=1000)),
                ("DueDate", models.DateField()),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("O", "Open"),
                            ("W", "Working"),
                            ("D", "Done"),
                            ("OD", "Overdue"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "Tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
