# Generated by Django 4.1.3 on 2022-12-23 17:52

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("Task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todotask",
            name="DueDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="todotask",
            name="Tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
