# Generated by Django 4.1.3 on 2022-12-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0003_alter_todotask_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todotask",
            name="Tags",
        ),
        migrations.AddField(
            model_name="todotask",
            name="Tags",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
